language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew build --scan -s

after_success:
  - ./gradlew sonarqube -Dsonar.organization=defano-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_KEY -Dsonar.exclusions=generated-src/**/* -Dsonar.branch.name=$TRAVIS_BRANCH