language: java

jdk:
- oraclejdk8

after_success:
- gradle sonarqube -Dsonar.organization=defano-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_KEY -Dsonar.exclusions=generated-src/**/* -Dsonar.branch.name=$TRAVIS_BRANCH